# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#development:

#  adapter: postgresql
#  pool: 10
#  username: postgres
#  password: postgres
#  min_messages: warning
#  host: 127.0.0.1
#  timeout: 5000
#  database: khbrah_development

common: &common
  adapter: postgresql
  username: postgres
  password: root # from psql setup, see Postgresql
  host: localhost

development:
  <<: *common
  database: desjardinsrealty_development

#test:
 # <<: *common
 # database: dashboard_test

production:
  <<: *common
  database: desjardinsrealty_development